name: Pipeline CD Caller with json conf
on:
  workflow_dispatch:
    inputs:
      image_version:
        type: string
        description: choose docker image version
        default: latest
jobs:
  call_cloudrun_pipeline_cd_with_json_conf:
    name: call cloudrun pipeline cd with json conf
    permissions:
      contents: 'read'
      id-token: 'write'
    uses: walido023/cicd-centralized-workflows-demo/.github/workflows/cd-cloudrun.yml@main
    with:
      image_version: ${{  inputs.image_version  }}
    secrets: inherit
