name: Pipeline CI Caller with json conf
on: workflow_dispatch
jobs:
  call_maven_pipeline_ci_json_conf:
    name: call maven pipeline ci with json conf
    permissions:
      contents: 'read'
      id-token: 'write'
    uses: walido023/cicd-centralized-workflows-demo/.github/workflows/ci-react-node-java-maven.yml@main
    secrets: inherit
